from enum import Enum


class PermissionLevel(str, Enum):
    PUBLIC_READ = "PUBLIC_READ"
    CUSTOMER_READ = "CUSTOMER_READ"
    CUSTOMER_WRITE = "CUSTOMER_WRITE"
    DESTRUCTIVE = "DESTRUCTIVE"
    ADMIN_ONLY = "ADMIN_ONLY"
    SYSTEM_ONLY = "SYSTEM_ONLY"


class IntentType(str, Enum):
    GENERAL_QUESTION = "GENERAL_QUESTION"
    GREETING = "GREETING"
    GRATITUDE = "GRATITUDE"
    STORE_INFO = "STORE_INFO"
    STYLING_ADVICE = "STYLING_ADVICE"
    SIZE_GUIDE = "SIZE_GUIDE"
    PRODUCT_SEARCH = "PRODUCT_SEARCH"
    PRODUCT_DETAILS = "PRODUCT_DETAILS"
    PRODUCT_RECOMMENDATION = "PRODUCT_RECOMMENDATION"
    CART_VIEW = "CART_VIEW"
    CART_ADD = "CART_ADD"
    CART_REMOVE = "CART_REMOVE"
    CART_UPDATE = "CART_UPDATE"
    WISHLIST_VIEW = "WISHLIST_VIEW"
    WISHLIST_ADD = "WISHLIST_ADD"
    WISHLIST_REMOVE = "WISHLIST_REMOVE"
    ORDER_LIST = "ORDER_LIST"
    ORDER_STATUS = "ORDER_STATUS"
    ORDER_TRACKING = "ORDER_TRACKING"
    ORDER_CREATE = "ORDER_CREATE"
    ORDER_CANCEL = "ORDER_CANCEL"
    ORDER_MODIFY = "ORDER_MODIFY"
    RETURN_POLICY = "RETURN_POLICY"
    POLICY_QUESTION = "POLICY_QUESTION"
    RETURN_REQUEST = "RETURN_REQUEST"
    ORDER_RETURN_REFUND = "ORDER_RETURN_REFUND"
    EXCHANGE_REQUEST = "EXCHANGE_REQUEST"
    ADDRESS_VIEW = "ADDRESS_VIEW"
    ADDRESS_CREATE = "ADDRESS_CREATE"
    ADDRESS_UPDATE = "ADDRESS_UPDATE"
    ADDRESS_DELETE = "ADDRESS_DELETE"
    COUPON = "COUPON"
    PAYMENT_QUESTION = "PAYMENT_QUESTION"
    SHIPPING_QUESTION = "SHIPPING_QUESTION"
    ACCOUNT_PROFILE = "ACCOUNT_PROFILE"
    HUMAN_SUPPORT = "HUMAN_SUPPORT"
    UNKNOWN = "UNKNOWN"


class ActionStatus(str, Enum):
    NONE = "NONE"
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REQUIRES_HUMAN = "REQUIRES_HUMAN"


class ConversationState(str, Enum):
    IDLE = "IDLE"
    UNDERSTANDING = "UNDERSTANDING"
    RETRIEVING = "RETRIEVING"
    PLANNING = "PLANNING"
    WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"


class SenderType(str, Enum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"
    TOOL = "TOOL"


class MessageType(str, Enum):
    TEXT = "TEXT"
    PRODUCT_LIST = "PRODUCT_LIST"
    PRODUCT = "PRODUCT"
    ORDER = "ORDER"
    ORDER_LIST = "ORDER_LIST"
    CART = "CART"
    CONFIRMATION = "CONFIRMATION"
    TOOL_STATUS = "TOOL_STATUS"
    SOURCE = "SOURCE"
    ERROR = "ERROR"
    ESCALATION = "ESCALATION"


class HandoffStatus(str, Enum):
    ACTIVE = "ACTIVE"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    WAITING_FOR_ADMIN = "WAITING_FOR_ADMIN"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
